export default [
  {
    title: 'Dashboard',
    route: 'dashboard-ecommerce',
    icon: 'HomeIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Agencies',
    route: 'agencies',
    icon: 'BarChartIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Bookings',
    route: 'bookings',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Jobs',
    route: 'jobs',
    icon: 'ToolIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Promotions',
    route: 'listPromotions',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'OnBoarding',
    route: 'onboardings',
    icon: 'BriefcaseIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Categories',
    route: 'categories',
    icon: 'ToolIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Sliders',
    route: 'sliders',
    icon: 'BarChartIcon',
    action: 'view',
    resource: 'navbar',
  },
  {
    title: 'Service Providers',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
    children: [{
      title: 'Indvidual',
      route: 'service_providers',
      action: 'view',
      resource: 'navbar',
    },
    {
      title: 'In House',
      route: 'listInHouseStaff',
      action: 'view',
      resource: 'user',
    },
    ],
  },
  {
    title: 'Users',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
    children: [{
      title: 'Residential',
      route: 'residentialUsers',
      action: 'view',
      resource: 'Settings',
    },
    {
      title: 'Commercial',
      route: 'commercialUsers',
      action: 'view',
      resource: 'user',
    },
    ],
  },
  {
    title: 'Transactions',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
    children: [{
      title: 'User Transactions',
      route: 'usersTransactions',
      action: 'view',
      resource: 'serviceProviderTransactions',
    },
    {
      title: 'Service Provider',
      route: 'serviceProviderTransactions',
      action: 'view',
      resource: 'serviceProviderTransactions',
    },
    ],
  },
  {
    title: 'Settings',
    icon: 'FileTextIcon',
    action: 'view',
    resource: 'navbar',
    children: [{
      title: 'Payment Gateways',
      route: 'listPaymentGateways',
      action: 'view',
      resource: 'serviceProviderTransactions',
    },
    {
      title: 'Global',
      route: 'globalSettings',
      action: 'view',
      resource: 'serviceProviderTransactions',
    },
    ],
  },
]
